### PR TITLE
docs: add contribution guideline

### PR DESCRIPTION
**Pull request by zeroFruit**
This is our basic contribution guideline. There are three sections.

1. Bootstrap Project
2. Development Workflow
3. Sending a Pull Request

## Bootstrap Project
This section contains how to set up our project for the first time.

## Development Workflow 
This section contains how to develop our project source code (such as adding features, do refactoring) in the format of step by step procedure.

## Sending a Pull Request
This section contains after you finish adding some codes how can you send a pull request to our repository.

----
After adding boilerplate code, this guideline should be added in the section of Backend, Frontend part.

### CODE REVIEW

**Review by mss8087old — COMMENTED** [review]
Good!

**Comment by zeroFruit** [comment]
@mss8087 If you think this is good, could you approve this pull request? You can approve this pr on this page

image

You can mark the 'approve' check box! Thx 👍

**Review by dkim94 — APPROVED** [review]
Good 2 :)

**Review by mss8087old — APPROVED** [review]
Approve!

**Pull request merged**
